services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASS: ${DATABASE_PASS:-password}
volumes:
  postgres_volume:
