 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/base_people", type: :request do
  
  # BasePerson. As you add validations to BasePerson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      BasePerson.create! valid_attributes
      get base_people_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      base_person = BasePerson.create! valid_attributes
      get base_person_url(base_person)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_base_person_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      base_person = BasePerson.create! valid_attributes
      get edit_base_person_url(base_person)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new BasePerson" do
        expect {
          post base_people_url, params: { base_person: valid_attributes }
        }.to change(BasePerson, :count).by(1)
      end

      it "redirects to the created base_person" do
        post base_people_url, params: { base_person: valid_attributes }
        expect(response).to redirect_to(base_person_url(BasePerson.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new BasePerson" do
        expect {
          post base_people_url, params: { base_person: invalid_attributes }
        }.to change(BasePerson, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post base_people_url, params: { base_person: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested base_person" do
        base_person = BasePerson.create! valid_attributes
        patch base_person_url(base_person), params: { base_person: new_attributes }
        base_person.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the base_person" do
        base_person = BasePerson.create! valid_attributes
        patch base_person_url(base_person), params: { base_person: new_attributes }
        base_person.reload
        expect(response).to redirect_to(base_person_url(base_person))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        base_person = BasePerson.create! valid_attributes
        patch base_person_url(base_person), params: { base_person: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested base_person" do
      base_person = BasePerson.create! valid_attributes
      expect {
        delete base_person_url(base_person)
      }.to change(BasePerson, :count).by(-1)
    end

    it "redirects to the base_people list" do
      base_person = BasePerson.create! valid_attributes
      delete base_person_url(base_person)
      expect(response).to redirect_to(base_people_url)
    end
  end
end
