# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bibclasses', type: :request do
  # Bibclasse. As you add validations to Bibclasse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Bibclasse.create! valid_attributes
      get bibclasses_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      πbibclasse = Bibclasse.create! valid_attributes
      get bibclass_url(bibclass)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bibclass_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      bibclasse = Bibclasse.create! valid_attributes
      get edit_bibclass_url(bibclass)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bibclasse' do
        expect do
          post bibclasses_url, params: { bibclasse: valid_attributes }
        end.to change(Bibclasse, :count).by(1)
      end

      it 'redirects to the created bibclasse' do
        post bibclasses_url, params: { bibclasse: valid_attributes }
        expect(response).to redirect_to(bibclass_url(@bibclass))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bibclasse' do
        expect do
          post bibclasses_url, params: { bibclasse: invalid_attributes }
        end.to change(Bibclasse, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bibclasses_url, params: { bibclasse: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested bibclasse' do
        bibclasse = Bibclasse.create! valid_attributes
        patch bibclass_url(bibclass), params: { bibclass: new_attributes }
        bibclasse.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the bibclasse' do
        bibclasse = Bibclasse.create! valid_attributes
        patch bibclass_url(bibclass), params: { bibclass: new_attributes }
        bibclasse.reload
        expect(response).to redirect_to(bibclass_url(bibclasse))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bibclasse = Bibclasse.create! valid_attributes
        patch bibclass_url(bibclass), params: { bibclass: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bibclasse' do
      bibclass = Bibclass.create! valid_attributes
      expect do
        delete bibclass_url(bibclass)
      end.to change(Bibclass, :count).by(-1)
    end

    it 'redirects to the bibclasses list' do
      bibclasse = Bibclasse.create! valid_attributes
      delete bibclass_url(bibclass)
      expect(response).to redirect_to(bibclasses_url)
    end
  end
end
