# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/book_people', type: :request do
  # BookPerson. As you add validations to BookPerson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BookPerson.create! valid_attributes
      get book_people_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      book_person = BookPerson.create! valid_attributes
      get book_person_url(book_person)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_book_person_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      book_person = BookPerson.create! valid_attributes
      get edit_book_person_url(book_person)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BookPerson' do
        expect do
          post book_people_url, params: { book_person: valid_attributes }
        end.to change(BookPerson, :count).by(1)
      end

      it 'redirects to the created book_person' do
        post book_people_url, params: { book_person: valid_attributes }
        expect(response).to redirect_to(book_person_url(BookPerson.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BookPerson' do
        expect do
          post book_people_url, params: { book_person: invalid_attributes }
        end.to change(BookPerson, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_people_url, params: { book_person: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested book_person' do
        book_person = BookPerson.create! valid_attributes
        patch book_person_url(book_person), params: { book_person: new_attributes }
        book_person.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the book_person' do
        book_person = BookPerson.create! valid_attributes
        patch book_person_url(book_person), params: { book_person: new_attributes }
        book_person.reload
        expect(response).to redirect_to(book_person_url(book_person))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_person = BookPerson.create! valid_attributes
        patch book_person_url(book_person), params: { book_person: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested book_person' do
      book_person = BookPerson.create! valid_attributes
      expect do
        delete book_person_url(book_person)
      end.to change(BookPerson, :count).by(-1)
    end

    it 'redirects to the book_people list' do
      book_person = BookPerson.create! valid_attributes
      delete book_person_url(book_person)
      expect(response).to redirect_to(book_people_url)
    end
  end
end
