# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/book_workers', type: :request do
  # BookWorker. As you add validations to BookWorker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      BookWorker.create! valid_attributes
      get book_workers_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      book_worker = BookWorker.create! valid_attributes
      get book_worker_url(book_worker)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_book_worker_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      book_worker = BookWorker.create! valid_attributes
      get edit_book_worker_url(book_worker)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new BookWorker' do
        expect do
          post book_workers_url, params: { book_worker: valid_attributes }
        end.to change(BookWorker, :count).by(1)
      end

      it 'redirects to the created book_worker' do
        post book_workers_url, params: { book_worker: valid_attributes }
        expect(response).to redirect_to(book_worker_url(BookWorker.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new BookWorker' do
        expect do
          post book_workers_url, params: { book_worker: invalid_attributes }
        end.to change(BookWorker, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post book_workers_url, params: { book_worker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested book_worker' do
        book_worker = BookWorker.create! valid_attributes
        patch book_worker_url(book_worker), params: { book_worker: new_attributes }
        book_worker.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the book_worker' do
        book_worker = BookWorker.create! valid_attributes
        patch book_worker_url(book_worker), params: { book_worker: new_attributes }
        book_worker.reload
        expect(response).to redirect_to(book_worker_url(book_worker))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        book_worker = BookWorker.create! valid_attributes
        patch book_worker_url(book_worker), params: { book_worker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested book_worker' do
      book_worker = BookWorker.create! valid_attributes
      expect do
        delete book_worker_url(book_worker)
      end.to change(BookWorker, :count).by(-1)
    end

    it 'redirects to the book_workers list' do
      book_worker = BookWorker.create! valid_attributes
      delete book_worker_url(book_worker)
      expect(response).to redirect_to(book_workers_url)
    end
  end
end
