 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/charsets", type: :request do
  
  # Charset. As you add validations to Charset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Charset.create! valid_attributes
      get charsets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      charset = Charset.create! valid_attributes
      get charset_url(charset)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_charset_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      charset = Charset.create! valid_attributes
      get edit_charset_url(charset)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Charset" do
        expect {
          post charsets_url, params: { charset: valid_attributes }
        }.to change(Charset, :count).by(1)
      end

      it "redirects to the created charset" do
        post charsets_url, params: { charset: valid_attributes }
        expect(response).to redirect_to(charset_url(Charset.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Charset" do
        expect {
          post charsets_url, params: { charset: invalid_attributes }
        }.to change(Charset, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post charsets_url, params: { charset: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested charset" do
        charset = Charset.create! valid_attributes
        patch charset_url(charset), params: { charset: new_attributes }
        charset.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the charset" do
        charset = Charset.create! valid_attributes
        patch charset_url(charset), params: { charset: new_attributes }
        charset.reload
        expect(response).to redirect_to(charset_url(charset))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        charset = Charset.create! valid_attributes
        patch charset_url(charset), params: { charset: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested charset" do
      charset = Charset.create! valid_attributes
      expect {
        delete charset_url(charset)
      }.to change(Charset, :count).by(-1)
    end

    it "redirects to the charsets list" do
      charset = Charset.create! valid_attributes
      delete charset_url(charset)
      expect(response).to redirect_to(charsets_url)
    end
  end
end
