require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/file_encodings', type: :request do
  # FileEncoding. As you add validations to FileEncoding, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      FileEncoding.create! valid_attributes
      get file_encodings_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      file_encoding = FileEncoding.create! valid_attributes
      get file_encoding_url(file_encoding)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_file_encoding_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      file_encoding = FileEncoding.create! valid_attributes
      get edit_file_encoding_url(file_encoding)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new FileEncoding' do
        expect do
          post file_encodings_url, params: { file_encoding: valid_attributes }
        end.to change(FileEncoding, :count).by(1)
      end

      it 'redirects to the created file_encoding' do
        post file_encodings_url, params: { file_encoding: valid_attributes }
        expect(response).to redirect_to(file_encoding_url(FileEncoding.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new FileEncoding' do
        expect do
          post file_encodings_url, params: { file_encoding: invalid_attributes }
        end.to change(FileEncoding, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post file_encodings_url, params: { file_encoding: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested file_encoding' do
        file_encoding = FileEncoding.create! valid_attributes
        patch file_encoding_url(file_encoding), params: { file_encoding: new_attributes }
        file_encoding.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the file_encoding' do
        file_encoding = FileEncoding.create! valid_attributes
        patch file_encoding_url(file_encoding), params: { file_encoding: new_attributes }
        file_encoding.reload
        expect(response).to redirect_to(file_encoding_url(file_encoding))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        file_encoding = FileEncoding.create! valid_attributes
        patch file_encoding_url(file_encoding), params: { file_encoding: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested file_encoding' do
      file_encoding = FileEncoding.create! valid_attributes
      expect do
        delete file_encoding_url(file_encoding)
      end.to change(FileEncoding, :count).by(-1)
    end

    it 'redirects to the file_encodings list' do
      file_encoding = FileEncoding.create! valid_attributes
      delete file_encoding_url(file_encoding)
      expect(response).to redirect_to(file_encodings_url)
    end
  end
end
