# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/receipts', type: :request do
  # Receipt. As you add validations to Receipt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Receipt.create! valid_attributes
      get receipts_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      receipt = Receipt.create! valid_attributes
      get receipt_url(receipt)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_receipt_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      receipt = Receipt.create! valid_attributes
      get edit_receipt_url(receipt)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Receipt' do
        expect do
          post receipts_url, params: { receipt: valid_attributes }
        end.to change(Receipt, :count).by(1)
      end

      it 'redirects to the created receipt' do
        post receipts_url, params: { receipt: valid_attributes }
        expect(response).to redirect_to(receipt_url(Receipt.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Receipt' do
        expect do
          post receipts_url, params: { receipt: invalid_attributes }
        end.to change(Receipt, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post receipts_url, params: { receipt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested receipt' do
        receipt = Receipt.create! valid_attributes
        patch receipt_url(receipt), params: { receipt: new_attributes }
        receipt.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the receipt' do
        receipt = Receipt.create! valid_attributes
        patch receipt_url(receipt), params: { receipt: new_attributes }
        receipt.reload
        expect(response).to redirect_to(receipt_url(receipt))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        receipt = Receipt.create! valid_attributes
        patch receipt_url(receipt), params: { receipt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested receipt' do
      receipt = Receipt.create! valid_attributes
      expect do
        delete receipt_url(receipt)
      end.to change(Receipt, :count).by(-1)
    end

    it 'redirects to the receipts list' do
      receipt = Receipt.create! valid_attributes
      delete receipt_url(receipt)
      expect(response).to redirect_to(receipts_url)
    end
  end
end
