# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/worker_roles', type: :request do
  # WorkerRole. As you add validations to WorkerRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      WorkerRole.create! valid_attributes
      get worker_roles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      worker_role = WorkerRole.create! valid_attributes
      get worker_role_url(worker_role)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_worker_role_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      worker_role = WorkerRole.create! valid_attributes
      get edit_worker_role_url(worker_role)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new WorkerRole' do
        expect do
          post worker_roles_url, params: { worker_role: valid_attributes }
        end.to change(WorkerRole, :count).by(1)
      end

      it 'redirects to the created worker_role' do
        post worker_roles_url, params: { worker_role: valid_attributes }
        expect(response).to redirect_to(worker_role_url(WorkerRole.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new WorkerRole' do
        expect do
          post worker_roles_url, params: { worker_role: invalid_attributes }
        end.to change(WorkerRole, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post worker_roles_url, params: { worker_role: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested worker_role' do
        worker_role = WorkerRole.create! valid_attributes
        patch worker_role_url(worker_role), params: { worker_role: new_attributes }
        worker_role.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the worker_role' do
        worker_role = WorkerRole.create! valid_attributes
        patch worker_role_url(worker_role), params: { worker_role: new_attributes }
        worker_role.reload
        expect(response).to redirect_to(worker_role_url(worker_role))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        worker_role = WorkerRole.create! valid_attributes
        patch worker_role_url(worker_role), params: { worker_role: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested worker_role' do
      worker_role = WorkerRole.create! valid_attributes
      expect do
        delete worker_role_url(worker_role)
      end.to change(WorkerRole, :count).by(-1)
    end

    it 'redirects to the worker_roles list' do
      worker_role = WorkerRole.create! valid_attributes
      delete worker_role_url(worker_role)
      expect(response).to redirect_to(worker_roles_url)
    end
  end
end
