# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bookfiles', type: :request do
  include ActionDispatch::TestProcess::FixtureFile

  # Bookfile. As you add validations to Bookfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      book_id: book.id,
      filetype_id: filetype.id,
      user_id: admin.id,
      compresstype_id: compresstype.id,
      file_encoding_id: file_encoding.id,
      charset_id: charset.id,
      filesize: 12_345,
      filename: 'sample.zip',
      bookdata: bookdata,
      revision_count: 1,
      note: 'test'
    }
  end

  let(:invalid_attributes) do
    {
      book_id: book.id,
      filetype_id: 'test',
      user_id: admin.id,
      compresstype_id: compresstype.id,
      file_encoding_id: file_encoding.id,
      charset_id: charset.id
    }
  end

  let(:book) { create(:book) }
  let(:filetype) { create(:filetype) }
  let(:admin) { create(:user, email: 'admin1@example.com', username: 'admin1') }
  let(:user) { create(:user) }
  let(:charset) { create(:charset) }
  let(:compresstype) { create(:compresstype) }
  let(:file_encoding) { create(:file_encoding) }
  let(:bookdata) { fixture_file_upload 'zip/sample.zip' }

  before { sign_in(admin) }

  describe 'GET /index' do
    it 'renders a successful response' do
      Bookfile.create! valid_attributes
      get admin_book_bookfiles_url(book)
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bookfile = Bookfile.create! valid_attributes
      get admin_book_bookfile_url(book, bookfile)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_book_bookfile_url(book)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      bookfile = Bookfile.create! valid_attributes
      get edit_admin_book_bookfile_url(bookfile.book, bookfile)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bookfile' do
        expect do
          post admin_book_bookfiles_url(book), params: { bookfile: valid_attributes }
        end.to change(Bookfile, :count).by(1)
      end

      it 'redirects to the created bookfile' do
        post admin_book_bookfiles_url(book), params: { bookfile: valid_attributes }
        expect(response).to redirect_to(admin_book_url(book))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bookfile' do
        expect do
          post admin_book_bookfiles_url(book), params: { bookfile: invalid_attributes }
        end.to change(Bookfile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_book_bookfiles_url(book), params: { bookfile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          book_id: book.id,
          filetype_id: filetype.id,
          user_id: user.id,
          compresstype_id: compresstype.id,
          file_encoding_id: file_encoding.id,
          charset_id: charset.id,
          filesize: 12_121,
          filename: 'sample.zip',
          revision_count: 1,
          note: 'test2'
        }
      end

      it 'updates the requested bookfile' do
        bookfile = Bookfile.create! valid_attributes
        patch admin_book_bookfile_url(book, bookfile), params: { bookfile: new_attributes }
        bookfile.reload
        expect(bookfile.note).to eq 'test2'
      end

      it 'redirects to the bookfile' do
        bookfile = Bookfile.create! valid_attributes
        patch admin_book_bookfile_url(book, bookfile), params: { bookfile: new_attributes }
        bookfile.reload
        expect(response).to redirect_to(admin_book_url(book))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bookfile = Bookfile.create! valid_attributes
        patch admin_book_bookfile_url(book, bookfile), params: { bookfile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bookfile' do
      bookfile = Bookfile.create! valid_attributes
      expect do
        delete admin_book_bookfile_url(book, bookfile)
      end.to change(Bookfile, :count).by(-1)
    end

    it 'redirects to the bookfiles list' do
      bookfile = Bookfile.create! valid_attributes
      delete admin_book_bookfile_url(book, bookfile)
      expect(response).to redirect_to(admin_book_url(book))
    end
  end
end
