# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/bookfiles', type: :request do
  # Bookfile. As you add validations to Bookfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Bookfile.create! valid_attributes
      get bookfiles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      bookfile = Bookfile.create! valid_attributes
      get bookfile_url(bookfile)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_bookfile_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      bookfile = Bookfile.create! valid_attributes
      get edit_bookfile_url(bookfile)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Bookfile' do
        expect do
          post bookfiles_url, params: { bookfile: valid_attributes }
        end.to change(Bookfile, :count).by(1)
      end

      it 'redirects to the created bookfile' do
        post bookfiles_url, params: { bookfile: valid_attributes }
        expect(response).to redirect_to(bookfile_url(Bookfile.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Bookfile' do
        expect do
          post bookfiles_url, params: { bookfile: invalid_attributes }
        end.to change(Bookfile, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post bookfiles_url, params: { bookfile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested bookfile' do
        bookfile = Bookfile.create! valid_attributes
        patch bookfile_url(bookfile), params: { bookfile: new_attributes }
        bookfile.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the bookfile' do
        bookfile = Bookfile.create! valid_attributes
        patch bookfile_url(bookfile), params: { bookfile: new_attributes }
        bookfile.reload
        expect(response).to redirect_to(bookfile_url(bookfile))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        bookfile = Bookfile.create! valid_attributes
        patch bookfile_url(bookfile), params: { bookfile: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested bookfile' do
      bookfile = Bookfile.create! valid_attributes
      expect do
        delete bookfile_url(bookfile)
      end.to change(Bookfile, :count).by(-1)
    end

    it 'redirects to the bookfiles list' do
      bookfile = Bookfile.create! valid_attributes
      delete bookfile_url(bookfile)
      expect(response).to redirect_to(bookfiles_url)
    end
  end
end
