# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/admin/works', type: :request do
  # Work. As you add validations to Work, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: 'テスト',
      title_kana: 'てすと',
      copyright_flag: false,
      started_on: Time.zone.parse('2021-05-06'),
      work_status_id: work_status.id,
      note: '備考1',
      user_id: user.id,
      kana_type_id: kana_type.id
    }
  end

  let(:invalid_attributes) do
    {
      title: nil,
      title_kana: 'てすと',
      copyright_flag: false,
      started_on: Time.zone.parse('2021-05-06'),
      work_status_id: 1,
      note: '備考1'
    }
  end

  let(:user) { create(:user, email: 'user2@example.com', username: 'user2') }
  let(:kana_type) { create(:kana_type) }
  let(:work_status) { create(:work_status) }

  before { sign_in(user) }

  describe 'GET /admin/works' do
    let(:work) { create(:work) }

    it 'renders a successful response' do
      get admin_works_url
      expect(response).to be_successful
    end
  end

  describe 'GET /admin/works/show' do
    let(:work) { create(:work) }

    it 'renders a successful response' do
      get admin_work_url(work)
      expect(response).to be_successful
    end
  end

  describe 'GET /admin/works/new' do
    it 'renders a successful response' do
      get new_admin_work_url
      expect(response).to be_successful
    end
  end

  describe 'GET /admin/works/edit' do
    let(:work) { create(:work) }

    it 'render a successful response' do
      get edit_admin_work_url(work)
      expect(response).to be_successful
    end
  end

  describe 'POST /adin/works/create' do
    context 'with valid parameters' do
      it 'creates a new Work' do
        expect do
          post admin_works_url, params: { work: valid_attributes }
        end.to change(Work, :count).by(1)
      end

      it 'redirects to the created work' do
        post admin_works_url, params: { work: valid_attributes }
        expect(response).to redirect_to(admin_work_url(Work.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Work' do
        expect do
          post admin_works_url, params: { work: invalid_attributes }
        end.to change(Work, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_works_url, params: { work: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /admin/works/update' do
    let!(:work) { create(:work) }

    context 'with valid parameters' do
      let(:new_attributes) do
        {
          title: 'テスト2',
          title_kana: 'てすとに',
          copyright_flag: false,
          started_on: Time.zone.parse('2021-05-06'),
          work_status_id: work_status.id,
          note: '備考2',
          user_id: user.id,
          kana_type_id: kana_type.id
        }
      end

      it 'updates the requested work' do
        patch admin_work_url(work), params: { work: new_attributes }
        work.reload
        expect(work.title).to eq 'テスト2'
      end

      it 'redirects to the work' do
        patch admin_work_url(work), params: { work: new_attributes }
        work.reload
        expect(response).to redirect_to(admin_work_url(work))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        patch admin_work_url(work), params: { work: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /admin/works/destroy' do
    let!(:work) { create(:work) }

    it 'destroys the requested work' do
      expect do
        delete admin_work_url(work)
      end.to change(Work, :count).by(-1)
    end

    it 'redirects to the works list' do
      delete admin_work_url(work)
      expect(response).to redirect_to(admin_works_url)
    end
  end
end
