# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/original_works', type: :request do
  # OriginalWork. As you add validations to OriginalWork, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: '底本名',
      publisher: '底本社',
      first_pubdate: '1998（平成10）年2月3日',
      input_edition: '1998（平成10）年2月3日第1刷',
      worktype_id: worktype.id,
      work_id: work.id,
      note: '備考'
    }
  end

  let(:invalid_attributes) do
    {
      title: nil
    }
  end

  let(:work) { create(:work) }
  let(:user) { create(:user) }
  let(:worktype) { create(:worktype) }

  before { sign_in(user) }

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_admin_work_original_work_url(work)
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      original_work = OriginalWork.create! valid_attributes
      get edit_admin_work_original_work_url(work, original_work)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new OriginalWork' do
        expect do
          post admin_work_original_works_url(work), params: { original_work: valid_attributes }
        end.to change(OriginalWork, :count).by(1)
      end

      it 'redirects to the created original_work' do
        post admin_work_original_works_url(work), params: { original_work: valid_attributes }
        expect(response).to redirect_to(admin_work_url(work))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new OriginalWork' do
        expect do
          post admin_work_original_works_url(work), params: { original_work: invalid_attributes }
        end.to change(OriginalWork, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post admin_work_original_works_url(work), params: { original_work: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          title: '底本名2'
        }
      end

      it 'updates the requested original_work' do
        original_work = OriginalWork.create! valid_attributes
        patch admin_work_original_work_url(work, original_work), params: { original_work: new_attributes }
        original_work.reload
        expect(original_work.title).to eq '底本名2'
      end

      it 'redirects to the original_work' do
        original_work = OriginalWork.create! valid_attributes
        patch admin_work_original_work_url(work, original_work), params: { original_work: new_attributes }
        original_work.reload
        expect(response).to redirect_to(admin_work_url(work))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        original_work = OriginalWork.create! valid_attributes
        patch admin_work_original_work_url(work, original_work), params: { original_work: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested original_work' do
      original_work = OriginalWork.create! valid_attributes
      expect do
        delete admin_work_original_work_url(work, original_work)
      end.to change(OriginalWork, :count).by(-1)
    end

    it 'redirects to the original_works list' do
      original_work = OriginalWork.create! valid_attributes
      delete admin_work_original_work_url(work, original_work)
      expect(response).to redirect_to(admin_work_url(work))
    end
  end
end
