services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shinonome_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shinonome_development"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - bundle_cache:/usr/local/bundle
      - node_modules:/workspace/node_modules
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/shinonome_development
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
    command: sleep infinity
    user: vscode
    working_dir: /workspace

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
