# Name of your application. Used to uniquely configure containers.
service: shinonome

# Name of the container image.
image: takahashim/shinonome

# Deploy to these servers.
servers:
  - <%= ENV['PRIMARY_HOST'] %>

# Credentials for your image host.
registry:
  username: takahashim
  password:
    - MRSK_REGISTRY_PASSWORD

env:
  clear:
    DATABASE_NAME: shinonome_production
    RAILS_LOG_TO_STDOUT: '1'
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_HOST
    - DATABASE_USER
    - DATABASE_PASS
    - SENDGRID_API_KEY
    - SKYLIGHT_AUTHENTICATION
    - MAIN_SITE_URL
    - SITE_NAME
    - RECEPTION_EMAIL
    - RAILS_ADMIN_PATH
    - PRIMARY_HOST
    - BUILDER_HOST

volumes:
  - "/srv/storage:/rails/storage"
  - "/srv/data/shinonome:/rails/data"

builder:
  dockerfile: Dockerfile.production
  arch: amd64
  remote: <%= ENV['BUILDER_HOST'] %>
  cache:
    type: registry
  args:
    GIT_SHA: <%= %x(git rev-parse HEAD) %>

sshkit:
  pool_idle_timeout: 1000

deploy_timeout: 100

# Configure custom arguments for Traefik
#
# Before deploy, create acme.json file on host:
#   mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json
proxy:
  host: reception.aozora-renewal.cloud
  app_port: 3000
  ssl: true
  healthcheck:
    interval: 3
    timeout: 10
